nix-conf: Properly report nix flake check failure in CI

diff --git a/bin/nix-conf b/bin/nix-conf
--- a/bin/nix-conf
+++ b/bin/nix-conf
@@ -262,7 +262,10 @@ case "$cmd" in
         update "$@";;
     "ci")
         update "$@"
-        nix flake check ~/nix/conf --override-input nixpkgs ~/nix/nixpkgs;;
+        if ! nix flake check ~/nix/conf --override-input nixpkgs ~/nix/nixpkgs; then
+           echo "nix flake check failed!!!" | tee -a ~/nix/out/"$HOST"/flake.error
+           exit 1
+        fi;;
     "build")
         build "$@";;
     "merge")
